title: "Disa Sariola"
remote_theme: dieghernan/chulapa
plugins:
  - jekyll-remote-theme
description: "PhD Candidate"

navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    children:
      - title: "Publications"
        url: /publications/
  - title: "Teaching"
    url: /teaching/
