title: "Disa Sariola"
theme: jekyll-theme-cayman
description: "PhD Candidate"

navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    children:
      - title: "Interests"
        url: /research/interests/
      - title: "Publications"
        url: /research/publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Contact"
    url: /contact/
