title: null
theme: jekyll-theme-primer
description: "PhD Candidate"

navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    children:
      - title: "Publications"
        url: /publications/
  - title: "Teaching"
    url: /teaching/
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      css: "/assets/css/style.css"
